import type { Metadata } from "next";
// import battlefieldstyles from "./battlefieldstyle.module.css";
export const metadata: Metadata = {
  title: "Battlefield",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
     {children}
    </div>
  );
}